
demo("graphics")
library("MASS")
data(Cars93)
ls()
#head(Cars93)
cat("Осинных Георгий Федорович\n")
cat("Задание a\n")
cat("Коэффициент ковариации зависимости Horsepower от Enginesize ", cov(Cars93[12], Cars93[13]), "\n") 
cat("Коэффициент кореляции зависимости Horsepower от Enginesize ",cor(Cars93[12], Cars93[13]), "\n\n")
cat("Задание b\n")
cat("Коэффициент ковариации зависимости Horsepower от Price", cov(Cars93[13], Cars93[5]), "\n")
cat("Коэффициент кореляции зависимости Horsepower от Price", cor(Cars93[13], Cars93[5]), "\n\n")
cat("Задание c\n")
cat("Коэффициент ковариации зависимости Enginesize от  Fuel.tank.capacity", cov(Cars93[12], Cars93[17]), "\n") 
cat("Коэффициент кореляции зависимости Enginesize от  Fuel.tank.capacity",cor(Cars93[12], Cars93[17]), "\n\n")
cat("Задание d\n")
cat("Коэффициент ковариации зависимости Passengers от Weight", cov(Cars93[17], Cars93[25]), "\n") 
cat("Коэффициент кореляции зависимости Passengers от Weight",cor(Cars93[17], Cars93[25]), "\n\n")
cat("Задание e\n")
cat("Коэффициент ковариации зависимости Weight от Price", cov(Cars93[25], Cars93[5]), "\n") 
cat("Коэффициент кореляции зависимости Weight от Price",cor(Cars93[25], Cars93[5]), "\n\n")
cat("Задание f\n")
cat("Коэффициент ковариации зависимости RPM от Horsepower", cov(Cars93[14], Cars93[13]), "\n") 
cat("Коэффициент кореляции зависимости RPM от Horsepower",cor(Cars93[14], Cars93[13]), "\n\n")
